-- Tests for the Lua hyperstyle implementation
local hyperstyle = require('hyperstyle')

describe('hyperstyle expansion', function()
  describe('expand_statement', function()
    it('expands simple statements', function()
      assert.equals('display: inline-block', hyperstyle.expand_statement('dib', true))
      assert.equals('display: block', hyperstyle.expand_statement('dblock', true))
      assert.equals('margin: 0', hyperstyle.expand_statement('m0', true))
      assert.equals('margin: 0 auto', hyperstyle.expand_statement('m0a', true))
    end)

    it('expands statements with numeric values', function()
      assert.equals('border-radius: 4px', hyperstyle.expand_statement('brad4', true))
      assert.equals('margin: 10px', hyperstyle.expand_statement('m10', true))
      assert.equals('margin: 10em', hyperstyle.expand_statement('m10m', true))
      assert.equals('padding: 15px', hyperstyle.expand_statement('pad15', true))
    end)

    it('expands statements with unit shortcuts', function()
      assert.equals('margin: 10px', hyperstyle.expand_statement('m10p', true))
      assert.equals('margin: 10px', hyperstyle.expand_statement('m10x', true))
      assert.equals('margin: 10em', hyperstyle.expand_statement('m10e', true))
      assert.equals('padding: 5em', hyperstyle.expand_statement('pad5m', true))
    end)

    it('expands property rules with default units', function()
      assert.equals('margin: 3px', hyperstyle.expand_statement('margin: 3', true))
      assert.equals('padding: 10px', hyperstyle.expand_statement('padding: 10', true))
      assert.equals('z-index: 1', hyperstyle.expand_statement('z-index: 1', true))
    end)

    it('expands value keywords', function()
      assert.equals('margin: auto', hyperstyle.expand_statement('margin: a', true))
      assert.equals('float: left', hyperstyle.expand_statement('float: l', true))
      assert.equals('display: none', hyperstyle.expand_statement('display: n', true))
    end)

    it('handles indentation', function()
      assert.equals('  display: block', hyperstyle.expand_statement('  dblock', true))
      assert.equals('    margin: 0', hyperstyle.expand_statement('    m0', true))
    end)

    it('works without colons for stylus/sass', function()
      assert.equals('display block', hyperstyle.expand_statement('dblock', false))
      assert.equals('margin 0 auto', hyperstyle.expand_statement('m0a', false))
    end)

    it('returns empty string for unrecognized patterns', function()
      assert.equals('', hyperstyle.expand_statement('unknown', true))
      assert.equals('', hyperstyle.expand_statement('xyz123', true))
    end)

    it('skips selector-like patterns', function()
      assert.equals('', hyperstyle.expand_statement('p:before', true))
      assert.equals('', hyperstyle.expand_statement('a:hover', true))
      assert.equals('', hyperstyle.expand_statement('div {', true))
    end)

    it('handles zero values without units', function()
      assert.equals('margin: 0', hyperstyle.expand_statement('margin: 0', true))
      assert.equals('padding: 0', hyperstyle.expand_statement('padding: 0', true))
    end)

    it('preserves complete rules with semicolons', function()
      assert.equals('', hyperstyle.expand_statement('margin: 10px;', true))
      assert.equals('', hyperstyle.expand_statement('display: block;', true))
    end)
  end)

  describe('expand_property', function()
    it('expands simple properties', function()
      assert.equals('margin:', hyperstyle.expand_property('m', true))
      assert.equals('padding:', hyperstyle.expand_property('pad', true))
      assert.equals('display:', hyperstyle.expand_property('di', true))
      assert.equals('background:', hyperstyle.expand_property('bg', true))
    end)

    it('expands full property names', function()
      assert.equals('margin:', hyperstyle.expand_property('margin', true))
      assert.equals('padding:', hyperstyle.expand_property('padding', true))
      assert.equals('border-radius:', hyperstyle.expand_property('border-radius', true))
    end)

    it('works without colons for stylus/sass', function()
      assert.equals('margin', hyperstyle.expand_property('m', false))
      assert.equals('padding', hyperstyle.expand_property('pad', false))
    end)

    it('handles indentation', function()
      assert.equals('  margin:', hyperstyle.expand_property('  m', true))
      assert.equals('    padding:', hyperstyle.expand_property('    pad', true))
    end)

    it('returns empty string for unrecognized properties', function()
      assert.equals('', hyperstyle.expand_property('unknown', true))
      assert.equals('', hyperstyle.expand_property('xyz', true))
    end)

    it('handles hyphenated properties', function()
      assert.equals('border-radius:', hyperstyle.expand_property('brad', true))
      assert.equals('text-align:', hyperstyle.expand_property('ta', true))
      assert.equals('font-weight:', hyperstyle.expand_property('fw', true))
    end)
  end)
end)